### PR TITLE
[Improvement] Add multiple networks

### PR DESCRIPTION
**Pull request by dn1s**
Implemented functionality of adding multiple networks at once to a vapp/vm.

### CODE REVIEW

**Comment by dn1s** [comment]
Need some help to get this checks working again :)

**Comment by bobbydeveaux** [comment]
Hi @dn1s  - the issues with the code are listed in Travis:

./vapp.go:90:92: first argument to append must be slice; have *types.NetworkConnection
./vapp.go:98:47: first argument to append must be slice; have *types.NetworkAssignment
./vapp.go:224:72: first argument to append must be slice; have *types.VAppNetworkConfiguration
./vapp.go:237:92: first argument to append must be slice; have *types.NetworkConnection
./vapp.go:244:47: first argument to append must be slice; have *types.NetworkAssignment
./vapp.go:258:83: invalid operation: vcomp.SourcedItem.InstantiationParams.NetworkConnectionSection.NetworkConnection[0] (type *types.NetworkConnection does not support indexing)
./vapp.go:258:195: invalid operation: vapptemplate.VAppTemplate.Children.VM[0].NetworkConnectionSection.NetworkConnection[0] (type *types.NetworkConnection does not support indexing)
./vapp.go:260:83: invalid operation: vcomp.SourcedItem.InstantiationParams.NetworkConnectionSection.NetworkConnection[0] (type *types.NetworkConnection does not support indexing)
./vapp.go:981:35: invalid operation: networksection.NetworkConnection[index] (type *types.NetworkConnection does not support indexing)
./vapp.go:982:35: invalid operation: networksection.NetworkConnection[index] (type *types.NetworkConnection does not support indexing)
./vapp.go:982:35: too many errors

Is that what you need help with, or are you okay looking into these? :)

Cheers

**Comment by dn1s** [comment]
In my IDE it's fine and I have no syntax errors.
It would be good if somebody else have another look :)

**Comment by bobbydeveaux** [comment]
Your branch works fine on my Mac too...

**Comment by bobbydeveaux** [comment]
Tests pass on my Mac.

**Comment by onmomo** [comment]
@dn1s your branch compiles on my side too. I think the problem is the types import `types "github.com/ukcloud/govcloudair/types/v56"`. Travis does `go get`on the current master since you changed and require the updated types in your branch it makes sense that the build fails for travis. Don't know how this can be fixed for Travis since go get can't reference a specific branch and relative imports are told to be bad practice in go?

**Comment by bobbydeveaux** [comment]
Great spot @onmomo 

In this case, given it's working for all 3 of us, including tests, I'm going to merge this branch into master.

Many thanks for this!

**Comment by bobbydeveaux** [comment]
Travis passing: https://travis-ci.org/UKCloud/govcloudair/builds/297978917

**Pull request merged**
